version: "3.8"

services:
  heimdall:
    image: linuxserver/heimdall:2.5.4
    container_name: heimdall
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/heimdall:/config
    ports:
      - 60211:443

  portainer:
    image: 6053537/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    environment:
      - TZ={TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIG_PATH}/portainer:/data
    ports:
      - 60212:9000

  emby:
    image: lovechen/embyserver:latest
    container_name: emby
    restart: unless-stopped
    environment:
      - UID=0
      - GID=0
      - GIDLIST=0
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/emby:/config
      - ${MEDIA_PATH}/video:/media/video
      - ${MEDIA_PATH}/family:/media/family
    ports:
      - 8096:8096
      - 1900:1900
      - 7359:7359
    devices:
      - /dev/vchiq:/dev/vchiq
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    network_mode: host
    restart: unless-stopped
    volumes:
      - ${CONFIG_PATH}/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8091:80/tcp"
    environment:
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/pihole/config:/etc/pihole
      - ${CONFIG_PATH}/pihole/dnsmasq.d:/etc/dnsmasq.d
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    restart: unless-stopped
    volumes:
      - ${CONFIG_PATH}/mosquitto:/mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    command: "mosquitto -c /mosquitto-no-auth.conf"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - ${CONFIG_PATH}/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    environment:
      - TZ=${TZ}
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  xiaoya:
    container_name: xiaoya
    image: xiaoyaliu/alist:latest
    restart: unless-stopped
    volumes:
      - ${CONFIG_PATH}/xiaoya:/data
    ports:
      - 80:80
      - 2345:2345
    environment:
      - TZ=${TZ}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  cloudflare:
    container_name: cloudflare
    image: cloudflare/cloudflared:latest
    restart: always
    command: "tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_LABEL_ENABLE: "true"
      TZ: "${TZ}"
      WATCHTOWER_NOTIFICATION_REPORT: "true"
      WATCHTOWER_NOTIFICATION_URL: >
        telegram://${TELEGRAM_TOKEN}@telegram?chats=5385841963
      WATCHTOWER_NOTIFICATION_TEMPLATE: |
        {{- if .Report -}}
          {{- with .Report -}}
        {{len .Scanned}} Scanned, {{len .Updated}} Updated, {{len .Failed}} Failed
              {{- range .Updated}}
        - {{.Name}} ({{.ImageName}}): {{.CurrentImageID.ShortID}} updated to {{.LatestImageID.ShortID}}
              {{- end -}}
              {{- range .Fresh}}
        - {{.Name}} ({{.ImageName}}): {{.State}}
            {{- end -}}
            {{- range .Skipped}}
        - {{.Name}} ({{.ImageName}}): {{.State}}: {{.Error}}
            {{- end -}}
            {{- range .Failed}}
        - {{.Name}} ({{.ImageName}}): {{.State}}: {{.Error}}
            {{- end -}}
          {{- end -}}
        {{- else -}}
          {{range .Entries -}}{{.Message}}{{"\n"}}{{- end -}}
        {{- end -}}
