version: "3"
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.128.2.0/24

services:
  heimdall:
    image: linuxserver/heimdall:2.5.4
    container_name: heimdall
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/heimdall:/config
    ports:
      - 60211:443
    networks:
      network:
        ipv4_address: 172.128.2.11

  portainer:
    image: 6053537/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    environment:
      - TZ={TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIG_PATH}/portainer:/data
    ports:
      - 60212:9000
    networks:
      network:
        ipv4_address: 172.128.2.12

  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 60213:8191
    networks:
      network:
        ipv4_address: 172.128.2.13

  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/jackett:/config
    ports:
      - 60214:9117
    networks:
      network:
        ipv4_address: 172.128.2.14

  jproxy:
    image: luckypuppy514/jproxy:latest
    container_name: jproxy
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ${CONFIG_PATH}/jproxy/database:/app/database
    ports:
      - 60215:8117
    networks:
      network:
        ipv4_address: 172.128.2.15

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info
      - JELLYFIN_TYPE=emby
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/jellyseerr:/app/config
    ports:
      - 60216:5055
    networks:
      network:
        ipv4_address: 172.128.2.16
    depends_on:
      - sonarr
      - radarr

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/radarr:/config
      - ${MEDIA_PATH}/video:/media/video
    ports:
      - 60217:7878
    networks:
      network:
        ipv4_address: 172.128.2.17
    depends_on:
      - jproxy
      - qbittorrent

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/sonarr:/config
      - ${MEDIA_PATH}/video:/media/video
    ports:
      - 60218:8989
    networks:
      network:
        ipv4_address: 172.128.2.18
    depends_on:
      - jproxy
      - qbittorrent

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=60219
    volumes:
      - ${CONFIG_PATH}/qbittorrent:/config
      - ${MEDIA_PATH}/video:/media/video
    ports:
      - 60219:60219
      - 60881:6881
      - 60881:6881/udp
    networks:
      network:
        ipv4_address: 172.128.2.19

  chinesesubfinder:
    image: allanpk716/chinesesubfinder:latest-lite
    container_name: chinesesubfinder
    restart: unless-stopped
    volumes:
      - ${CONFIG_PATH}/chinesesubfinder:/config
      - ${MEDIA_PATH}/video:/media/video
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PERMS=true
      - UMASK=022
    hostname: chinesesubfinder
    ports:
      - 60221:19035
      - 19037:19037
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    networks:
      network:
        ipv4_address: 172.128.2.21

  emby:
    image: lovechen/embyserver:latest
    container_name: emby
    restart: unless-stopped
    environment:
      - UID=0
      - GID=0
      - GIDLIST=0
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/emby:/config
      - ${MEDIA_PATH}/video:/media/video
      - ${MEDIA_PATH}/family:/media/family
    ports:
      - 60220:8096
    networks:
      network:
        ipv4_address: 172.128.2.20
    devices:
      - /dev/vchiq:/dev/vchiq

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    network_mode: host
    restart: unless-stopped
    volumes:
      - ${CONFIG_PATH}/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8091:80/tcp"
    environment:
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/pihole/config:/etc/pihole
      - ${CONFIG_PATH}/pihole/dnsmasq.d:/etc/dnsmasq.d
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    restart: unless-stopped
    volumes:
      - ${CONFIG_PATH}/mosquitto:/mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    command: "mosquitto -c /mosquitto-no-auth.conf"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - ${CONFIG_PATH}/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    environment:
      - TZ=${TZ}
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  xiaoya:
    container_name: xiaoya
    image: xiaoyaliu/alist:latest
    restart: always
    volumes:
      - ${CONFIG_PATH}/xiaoya:/data
    ports:
      - 80:80
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
